language: ruby

jdk: openjdk8

cache:
  - bundler

script:
  - bundle exec rake test
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bundle exec rake publish

notifications:
  slack:
    secure: "K85xR9b1VQMK2c3KpXjho4WBz1fTIUSfsmLCMFRkYY8ykOoH7fjBLRJRQtAOMfjUNfjDt+VMwFTky0F8lMmZRMnBBYZ8mTzhmKjJY0ToWLiDIJm48ncPleJRzMR0ku9xU7x1DHB6QEMu6DFXkgoe4/b0VOsFwYzQGmelfZNhD6U="

